package net.sourceforge.schemaspy.view;

import java.io.*;
import java.util.*;
import net.sourceforge.schemaspy.model.*;
import net.sourceforge.schemaspy.util.*;

public class HtmlFormatter {
    protected void writeHeader(Database db, Table table, String text, LineWriter out) throws IOException {
        out.writeln("<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>");
        out.writeln("<html>");
        out.writeln("<head>");
        out.write("  <title>SchemaSpy - ");
        out.write(getDescription(db, table, text, false));
        out.writeln("</title>");
        out.write("  <link rel=stylesheet href='");
        if (table != null)
            out.write("../");
        out.writeln("schemaSpy.css' type='text/css'>");
        out.writeln("  <meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>");
        out.writeln("  <SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='" + (table == null ? "" : "../") + "schemaSpy.js'></SCRIPT>");
        out.writeln("</head>");
        out.writeln("<body onload='syncOptions()'>");
        out.writeln("<table width='100%' border='0' cellpadding='0'>");
        out.writeln(" <tr>");
        out.write("  <td class='heading' valign='top'><h1>");
        if (table == null)
            out.write("SchemaSpy Analysis of ");
        out.write(getDescription(db, table, text, true));
        out.writeln("</h1></td>");
        out.writeln("  <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'>Generated by<br><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></td>");
        out.writeln(" </tr>");
        out.writeln("</table>");
        if (table == null) {
            out.write("<table><tr><td class='tableHolder'>");
            out.write("Generated by <span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span> on ");
            out.write(db.getConnectTime());
            out.writeln("</td></tr></table>");
        }
    }

    protected void writeTableOfContents(boolean showRelationships, boolean showOrphans, LineWriter html) throws IOException {
        writeTableOfContents(showRelationships, showOrphans, false, html);
    }

    protected void writeTableOfContents(boolean showRelationships, boolean showOrphans, boolean showLogo, LineWriter html) throws IOException {
        String path = getPathToRoot();
        showLogo = showLogo && sourceForgeLogoEnabled();
        html.writeln("<table width='100%'>");
        html.writeln(" <tr>");
        html.writeln("  <td class='tableHolder'>");
        html.write("   ");
        if (!isMainIndex())
            html.write("<a href='" + path + "index.html'>Tables</a>&nbsp;&nbsp;");
        if (showRelationships)
            html.write("<a href='" + path + "relationships.html' title='Graphical view of table relationships'>Relationships Graph</a>&nbsp;&nbsp;");
        if (showOrphans)
            html.write("<a href='" + path + "utilities.html' title='Graphical view of tables with neither parents nor children'>Utility Tables Graph</a>&nbsp;&nbsp;");
        if (!isConstraintsPage())
            html.write("<a href='" + path + "constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a>&nbsp;&nbsp;");
        if (!isAnomaliesPage())
            html.write("<a href='" + path + "anomalies.html' title=\"Things that aren't quite right\">Anomalies</a>&nbsp;&nbsp;");
        if (!isColumnsPage())
            html.write("<a href='" + path + "columns.html' title=\"All of the columns in the schema\">Columns</a>");
        html.writeln("");
        html.writeln("  </td>");
        if (showLogo)
            html.writeln("  <td class='tableHolder' align='right' valign='top'><a href='http://sourceforge.net' target='_blank'><img src='http://sourceforge.net/sflogo.php?group_id=137197&amp;type=1' alt='SourceForge.net' border='0' height='31' width='88'></a></td>");
        html.writeln(" </tr>");
        html.writeln("</table>");
    }

    protected String getDescription(Database db, Table table, String text, boolean hoverHelp) {
        StringBuffer description = new StringBuffer();
        if (table != null) {
            if (table.isView())
                description.append("View ");
            else
                description.append("Table ");
        }
        if (hoverHelp)
            description.append("<span title='Database'>");
        description.append(db.getName());
        if (hoverHelp)
            description.append("</span>");
        if (db.getSchema() != null) {
            description.append('.');
            if (hoverHelp)
                description.append("<span title='Schema'>");
            description.append(db.getSchema());
            if (hoverHelp)
                description.append("</span>");
        }
        if (table != null) {
            description.append('.');
            if (hoverHelp)
                description.append("<span title='Table'>");
            description.append(table.getName());
            if (hoverHelp)
                description.append("</span>");
        }
        if (text != null) {
            description.append(" - ");
            description.append(text);
        }

        return description.toString();
    }

    protected boolean sourceForgeLogoEnabled() {
        // I hate this hack, but I don't want to have to pass this boolean everywhere...
        return System.getProperty("sourceforgelogo") != null;
    }

    protected void writeLegend(boolean tableDetails, LineWriter out) throws IOException {
        writeLegend(tableDetails, true, out);
    }

    protected void writeLegend(boolean tableDetails, boolean graphDetails, LineWriter out) throws IOException {
        out.writeln(" <table class='legend' border='0'>");
        out.writeln("  <tr>");
        out.writeln("   <td class='dataTable' valign='bottom'>Legend:</td>");
        if (sourceForgeLogoEnabled())
            out.writeln("   <td class='tableHolder' align='right' valign='top'><a href='http://sourceforge.net' target='_blank'><img src='http://sourceforge.net/sflogo.php?group_id=137197&amp;type=1' alt='SourceForge.net' border='0' height='31' width='88'></a></td>");
        out.writeln("  </tr>");
        out.writeln("  <tr><td class='tableHolder' colspan='2'>");
        out.writeln("   <table class='dataTable' border='1'>");
        out.writeln("    <tbody>");
        out.writeln("    <tr><td class='primaryKey'>Primary key columns</td></tr>");
        out.writeln("    <tr><td class='indexedColumn'>Columns with indexes</td></tr>");
        if (tableDetails)
            out.writeln("    <tr class='impliedRelationship'><td>Implied relationships</td></tr>");
        // comment this out until I can figure out a clean way to embed image references
        //out.writeln("    <tr><td class='tableHolder'>Arrows go from children (foreign keys)" + (tableDetails ? "<br>" : " ") + "to parents (primary keys)</td></tr>");
        if (graphDetails) {
            out.writeln("    <tr><td class='ignoredColumn'>Ignored column relationships</td></tr>");
            out.writeln("    <tr><td class='tableHolder'>Dashed lines show" + (tableDetails ? "<br>" : " ") + "implied relationships</td></tr>");
        }
        out.writeln("   </table>");
        out.writeln("  </td></tr>");
        out.writeln(" </table>");
        out.writeln("    Please <a href='http://sourceforge.net/donate/index.php?group_id=137197' target='_blank'>support</a> this project&nbsp;");
    }

    protected void writeExcludedColumns(Set excludedColumns, LineWriter html) throws IOException {
        if (excludedColumns.size() > 0) {
            html.writeln("<span class='ignoredRelationship'>");
            html.writeln("<br>These columns were not evaluated during analysis: ");
            Iterator iter = excludedColumns.iterator();
            while (iter.hasNext()) {
                TableColumn column = (TableColumn)iter.next();
                html.write("<a href=\"" + getPathToRoot() + "tables/");
                html.write(column.getTable().getName());
                html.write(".html\">");
                html.write(column.getTable().getName());
                html.write(".");
                html.write(column.getName());
                html.writeln("</a>&nbsp;");
            }
            html.writeln("</span>");
        }
    }


    protected void writeFooter(LineWriter out) throws IOException {
        out.writeln("</body>");
        out.writeln("</html>");
    }

    /**
     * Override if your output doesn't live in the root directory.
     * If non blank must end with a trailing slash.
     *
     * @return String
     */
    protected String getPathToRoot() {
        return "";
    }
    /**
     * Override and return true if you're the main index page.
     *
     * @return boolean
     */
    protected boolean isMainIndex() {
        return false;
    }

    /**
     * Override and return true if you're the constraints page
     *
     * @return boolean
     */
    protected boolean isConstraintsPage() {
        return false;
    }

    /**
     * Override and return true if you're the anomalies page
     *
     * @return boolean
     */
    protected boolean isAnomaliesPage() {
        return false;
    }

    /**
     * Override and return true if you're the columns page
     *
     * @return boolean
     */
    protected boolean isColumnsPage() {
        return false;
    }
}
